module.exports = [
  {
    id: "1",
    name: "BANANA SPLIT",
    amount:2,
    image:
      "https://www.paulinacocina.net/wp-content/uploads/2021/12/banana-split-helado.jpg",
    available: true,
    type: "Dessert",
    Fat: "High",
    Sodium: "Low",
    Sugar: "High",
    price: 6,
    description:
      "Ice cream served on a banana cut in half usually garnished with syrup, fruits, nuts and whipped cream.",
    discount: 0,
    review: [],
  },
  {
    id: "2",
    name: "ASIA EXPRESS CHINESE",
    amount:5,
    image:
      "https://www.visitconcordca.com/imager/s3-us-west-1_amazonaws_com/concord-2018/craft/Asia-Express-Chinese-Food_78c77f7e90fd3bfb1d9860e623e7e9a0.jpg",
    available: true,
    type: "Salad",
    Fat: "High",
    Sodium: "High",
    Sugar: "Medium",
    price: 4,
    description:
      "Asia Express Chinese Food offers delicious dining and takeout to Concord, CA",
    discount: 1,
    review: [],
  },
  {
    id: "3",
    name: "BAMBINO’S ITALIAN",
    amount:1,
    image:
      "https://www.visitconcordca.com/imager/s3-us-west-1_amazonaws_com/concord-2018/craft/Local-Buisinesses/bambinos_78c77f7e90fd3bfb1d9860e623e7e9a0.jpg",
    available: true,
    type: "Main dish",
    Fat: "Low",
    Sodium: "Low",
    Sugar: "Medium",
    price: 4,
    description:
      "Bambino’s is an Italian favorite here in Concord. Take a trip to Italy when you visit and try authentic",
    discount: 2,
    review: [],
  },
  {
    id: "4",
    name: "MOZZARELLA STICKS",
    amount:3,
    image:
      "https://lacteostonutti.com.ar/wp-content/uploads/2021/01/6-7-1080x675.jpg",
    available: true,
    type: "Appetizer",
    Fat: "High",
    Sodium: "High",
    Sugar: "Low",
    price: 3,
    description:
      "Crunchy on the outside and delicious on the inside. A classic among appetizers",
    discount: 0,
    review: [],
  },
  {
    id: "5",
    name: "BEEF STEW",
    amount:5,
    image:
      "https://www.onceuponachef.com/images/2011/02/beef-stew-with-carrots-potatoes.jpg",
    available: true,
    type: "Main dish",
    Fat: "High",
    Sodium: "Medium",
    Sugar: "Medium",
    price: 6,
    description:
      "This classic French beef stew is the ultimate cold weather comfort food. After a few hours in the oven, the meat becomes meltingly tender and enveloped in a rich wine sauce",
    discount: 2,
    review: [],
  },
  {
    id: "6",
    name: "OLIVE CHEESE SKEWERS",
    amount:4,
    image:
      "https://assets.kraftfoods.com/recipe_images/opendeploy/Mediterranean-Starter-Sticks-53988_640x428.jpg",
    available: true,
    type: "Appetizer",
    Fat: "Low",
    Sodium: "Medium",
    Sugar: "Low",
    price: 1,
    description: "They are perfect for any occasion!",
    discount: 0,
    review: [],
  },
  {
    id: "7",
    name: "SEPTIMA MALBEC WINE",
    amount:2,
    image: "https://laverdadonline.com/wp-content/uploads/2022/05/copa-2.jpg",
    available: true,
    type: "Drink",
    Fat: "Medium",
    Sodium: "Medium",
    Sugar: "High",
    price: 8,
    description: "The real treasure of the winery",
    discount: 1,
    review: [],
  },
  {
    id: "8",
    name: "IMPERIAL BEER",
    amount:1,
    image:
      "https://www.history.com/.image/t_share/MTk1NTU5MDQ0MTYzODM5MDM3/gettyimages-1386915196.jpg",
    available: true,
    type: "Drink",
    Fat: "High",
    Sodium: "Medium",
    Sugar: "Low",
    price: 2,
    description:
      "Was born in Ortega brewery, combines the traditional German beer with the taste of Costa Rica",
    discount: 0,
    review: [],
  },
  {
    id: "9",
    name: "BEST BURGER",
    amount:3,
    image: "https://www.likeburger.com.ar/images/fotos/8.jpg",
    available: true,
    type: "Main dish",
    Fat: "High",
    Sodium: "High",
    Sugar: "Medium",
    price: 7,
    description:
      "A very meticulous work in the creation of our Meat, Potato Bread, sauces and toppings",
    discount: 2,
    review: [],
  },
  {
    id: "10",
    name: "AREPAS",
    amount:5,
    image:
      "https://nomadparadise.com/wp-content/uploads/2020/07/colombian-food-01-768x480.jpg.webp",
    available: true,
    type: "Main dish",
    Fat: "Medium",
    Sodium: "Medium",
    Sugar: "Medium",
    price: 5,
    description:
      "Traditional flat cake from Colombia, made of corn flour and water that can be filled with a variety of tasty fillings",
    discount: 1,
    review: [],
  },
  {
    id: "11",
    name: "SODA WITH ICE",
    amount:3,
    image:
      "https://thumbs.dreamstime.com/b/glasses-cola-orange-soda-drink-lemonade-sparkling-water-white-background-ice-cubes-154052973.jpg",
    available: true,
    type: "Drink",
    Fat: "Medium",
    Sodium: "Medium",
    Sugar: "High",
    price: 2,
    description:
      "Glasses of cola, orange and sparkling lemonade with ice cubes",
    discount: 0,
    review: [],
  },
  {
    id: "12",
    name: "CAESAR SALAD",
    amount:5,
    image:
      "https://img.taste.com.au/8-PjS8DG/w720-h480-cfill-q80/taste/2016/11/traditional-caesar-salad-974-1.jpeg",
    available: true,
    type: "Salad",
    Fat: "Low",
    Sodium: "Medium",
    Sugar: "Low",
    price: 5,
    description:
      "The delicious and classic Caesar salad, and although it is a classic, you can't even imagine how delicious it is!",
    discount: 1,
    review: [],
  },
  {
    id: "13",
    name: "ISRAELI FALAFEL",
    amount:1,
    image:
      "https://recetasarabes.com/wp-content/img-recetas-arabes/2012/03/falafel-3.jpg",
    available: true,
    type: "Main dish",
    Fat: "Medium",
    Sodium: "Medium",
    Sugar: "Low",
    price: 5,
    description:
      "Chickpea meatballs between breads, simple and delicious. An option full of nutrients, which is highly valued by vegetarians",
    discount: 1,
    review: [],
  },
  {
    id: "14",
    name: "WALDORF SALAD",
    amount:5,
    image:
      "https://images-gmi-pmc.edge-generalmills.com/3eda262b-a41b-4fca-9806-b5c33e982910.jpg",
    available: true,
    type: "Salad",
    Fat: "Low",
    Sodium: "Medium",
    Sugar: "Medium",
    price: 3,
    description:
      "This refreshing salad is perfect for a holiday meal. Serve it in your prettiest glass bowl and garnish it as you like.",
    discount: 0,
    review: [],
  },
  {
    id: "15",
    name: "CUSTARD PUDDING",
    amount:4,
    image:
      "https://cookingwithdog.com/wp-content/uploads/2017/01/custard-pudding-00-1024x576.jpg",
    available: true,
    type: "Dessert",
    Fat: "High",
    Sodium: "Low",
    Sugar: "High",
    price: 5,
    description:
      "This delicious custard pudding is made with eggs, sugar, milk and an appetizing caramel",
    discount: 1,
    review: [],
  },
  {
    id: "16",
    name: "BATTERED FRIED SQUIDS",
    image: "https://vinomanos.com/wp-content/uploads/2021/01/Rabas.jpg",
    available: true,
    type: "Appetizer",
    Fat: "High",
    Sodium: "Medium",
    Sugar: "Low",
    amount:3,
    price: 8,
    description:
      "It's a true classic and a household favorite. And what's more, everyone loves it!",
    discount: 1,
    review: [],
  },
  {
    id: "17",
    name: "CHOCOLATE VOLCANO",
    amount:1,
    image:
      "https://www.hersheyland.com/content/dam/Hersheyland_Mexico/es_mx/recipes/recipe-images/Volc%C3%A1n%20de%20Chocolate%20Hershey's.jpg",
    available: true,
    type: "Dessert",
    Fat: "High",
    Sodium: "Medium",
    Sugar: "High",
    price: 7,
    description:
      "Our Volcano is a delicious and elegant dessert made of chocolate bread filled with liquid chocolate and decorated with... More chocolate!",
    discount: 0,
    review: [],
  },
  {
    id: "18",
    name: "FRUIT JUICE",
    amount:2,
    image:
      "https://d2jx2rerrg6sh3.cloudfront.net/image-handler/ts/20180426060615/ri/673/picture/2018/4/shutterstock_1By_stockcreations.jpg",
    available: true,
    type: "Drink",
    Fat: "Low",
    Sodium: "Low",
    Sugar: "High",
    price: 2,
    description:
      "Delicious 100% natural juice, freshly prepared and ready to be enjoyed with your meal",
    discount: 0,
    review: [],
  },
];
